name: Docker Build Dispatch

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name to build and push'
        required: true
  pull_request:
    branches:
      - main

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branchName || '' }}
    
    - name: Set REPO_NAME from GitHub repository
      run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Extract branch name
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BRANCH_OR_TAG="pr-${{ github.event.number }}"
        else
          BRANCH_OR_TAG="${{ github.event.inputs.branchName || github.ref }}"
          CLEANED_REF="${BRANCH_OR_TAG#refs/heads/}"
          CLEANED_REF="${CLEANED_REF#refs/tags/}"
          BRANCH_OR_TAG=$CLEANED_REF
        fi
        echo "BRANCH_OR_TAG=$BRANCH_OR_TAG" >> $GITHUB_ENV

    - name: Extract version
      run: echo "PROJECT_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:${{ env.BRANCH_OR_TAG }}
          ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:${{ env.PROJECT_VERSION }} 